//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Housing_Simplified
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plot
    {
        public int plot_id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Size { get; set; }
        public int Price { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsSold { get; set; }
        public string Owner_Name { get; set; }
        public Nullable<int> Owner_Phone { get; set; }
    }
}
